changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Bug Fixes
      labels:
        - bugfix
    - title: Maintenance
      labels:
        - maintenance
    - title: Has Pre/Post release actions
      labels:
        - pre-deployment-au
        - pre-deployment-ca
        - post-deployment-au
        - post-deployment-ca
    - title: New features
      labels:
        - feature
    - title: Other Changes
      labels:
        - "*"
